// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzupQqwXnViVKkwe7aEx5Oecvm1SIw-vY',
    appId: '1:93424872011:web:9e1f58c75a125d53737bce',
    messagingSenderId: '93424872011',
    projectId: 'meditation-by-vk-89927',
    authDomain: 'meditation-by-vk-89927.firebaseapp.com',
    storageBucket: 'meditation-by-vk-89927.firebasestorage.app',
    measurementId: 'G-9BHFQHQKKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC39vVURaV9BYnAqQXOIH0dB1vMudcAaS0',
    appId: '1:93424872011:android:fd80c9cbb252fce8737bce',
    messagingSenderId: '93424872011',
    projectId: 'meditation-by-vk-89927',
    storageBucket: 'meditation-by-vk-89927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bGajUwDeymUkyo80ZnPw17sNz7NaKK4',
    appId: '1:93424872011:ios:a204b0ba79fedec8737bce',
    messagingSenderId: '93424872011',
    projectId: 'meditation-by-vk-89927',
    storageBucket: 'meditation-by-vk-89927.firebasestorage.app',
    iosBundleId: 'com.romaninc.upmeditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bGajUwDeymUkyo80ZnPw17sNz7NaKK4',
    appId: '1:93424872011:ios:4bd989ae6a90d521737bce',
    messagingSenderId: '93424872011',
    projectId: 'meditation-by-vk-89927',
    storageBucket: 'meditation-by-vk-89927.firebasestorage.app',
    iosBundleId: 'com.example.meditationByVk',
  );
}